export const SIGN_IN_USER = 'REDUX_SAGA_SIGN_IN_USER';
export const SIGN_IN_USER_SUCCESS = 'REDUX_SAGA_SIGN_IN_USER_SUCCESS';
export const SIGN_IN_USER_ERROR = 'REDUX_SAGA_SIGN_IN_USER_ERROR';

export const SIGN_UP_USER = 'REDUX_SAGA_SIGN_UP_USER';
export const SIGN_UP_USER_SUCCESS = 'REDUX_SAGA_SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_ERROR = 'REDUX_SAGA_SIGN_UP_USER_ERROR';